### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kidonng** [kidonng/ncuhome-2019-winter-assignment#1]
- [x] Topics: Auto refresh
- [x] Topic: Related events
- [x] Topic: Event tracking
